### ISSUE TITLE
avoid packages that cannot be installed?

### ISSUE THREAD

**Issue by cboettig** [ropensci-archive/ropkgs#1]
e.g. https://github.com/ropensci/ICES is just a placeholder, so I don't want to list it.  for drat, I want to get a list of all packages that can successfully be installed (e.g. will need a DESCRIPTION file at least). 

Currently I grab all the packages indicated as `good`: https://github.com/cboettig/drat/blob/gh-pages/ropensci.R but that is picking up ICES.

**Comment by sckott** [comment]
@cboettig looking at this, will make some change to the registry

**Comment by cboettig** [comment]
Cool, thanks.  

drat.builder is also tripping up on https://github.com/ropensci/rbefdata, kind of a drat.builder issue since it appears the problem is just that the package doesn't have the DESCRIPTION at the root level.

**Comment by sckott** [comment]
Okay. Would it make sense to have another entry that gives the root of the R pkg in the github repo? like `"root": "rbefdata"` in this case. And would be `"root": "/"` or `"root": ""` for pkgs in the root of the repo

**Comment by cboettig** [comment]
yup, that would be awesome.

**Comment by sckott** [comment]
@cboettig okay, updated

see some new fields `installable`, `root`, `fork`

note that `installable` can be `TRUE` even if the package has `status=deprecated/hiatus`

now ICES has:

``` json
"status": "hiatus",
"installable": false,
```

**Comment by cboettig** [comment]
Cool.  I wonder if it would be possible to get the current travis status of
each package too?

**Comment by sckott** [comment]
thinking on that

**Comment by cboettig** [comment]
@sckott looks like redland-bindings is being listed as installable but shouldn't be?

**Comment by sckott** [comment]
right, it does install for me since I already have it's dependencies installed, though I guess for many it probably won't, I'll change

**Comment by cboettig** [comment]
Ah, I see, it looks like ropkgs is listing the the root directory as `""` instead of `"R/redland"`?  if it installs with it's dependencies in place than that seems valid to list as 'installable'

**Comment by sckott** [comment]
@cboettig Shoot, i'll fix that

**Comment by sckott** [comment]
@cboettig okay, listed with root as `R/redland`, tested, installs with `devtools::install_github("redland-bindings", subdir = "R/redland")`
